# fly.toml app configuration file generated for showcaseme on 2024-09-10T23:19:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'showcaseme'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
